apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-worker-order-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  POD_NAME: "go-worker-order.k8"
  API_VERSION: "1.0"
  #DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_HOST: "db-aurora-arch-01-us-east-2.cluster-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  SETPOD_AZ: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-xray-collector.default.svc.cluster.local:4317"
  ENV: "dev"
  QUEUE_URL_ORDER: "https://sqs.us-east-2.amazonaws.com/908671954593/order.fifo"
  AWS_REGION: "us-east-2"
  POD_QUEUE_TYPE: "sqs"