apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: &component-name go-worker-order-hpa
  namespace: test-a
  labels:
    app: *component-name
spec:
  scaleTargetRef:
    name: go-worker-order
  pollingInterval: 30
  cooldownPeriod:  60
  idleReplicaCount: 0 # Optional. Default: 0
  minReplicaCount: 0 # Optional. Default: 0
  maxReplicaCount: 2 # Optional. Default: 6
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: https://sqs.us-east-2.amazonaws.com/908671954593/order.fifo
      queueLength: "5"
      awsRegion: us-east-2
      identityOwner: operator
    authenticationRef:
      name: keda-auth-go-worker-order